// <auto-generated />
namespace EQ_Inva_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedmanagerValidatedField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmanagerValidatedField));
        
        string IMigrationMetadata.Id
        {
            get { return "201912020100519_addedmanagerValidatedField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
